apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 453489041264.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 453489041264.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: 3aa15a72
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
